---
- hosts: app_server
  tasks:
    - import_role:
        name: PYTHON

    - name: creation du conteneur
      docker_container:
       name: test_app
       image: "{{ image_prod }}"
       ports: '8081:8085'
       state: started
       command: java -jar /usr/bin/devops-1.0.war
