---
- hosts: test_server
  tasks:
    - import play_book: python.yml

    - name: creation du conteneur
      docker_container:
       name: test_app
       image: "{{ image }}"
       ports: '8080:8080'
       state: started
       command: java -jar /usr/bin/devops-1.0.war
