---
- hosts: app_server
  tasks:
    - name: install epel-release
      yum:
       name: epel-release
       state: present

    - name: install pip
      yum:
       name: python-pip
       state: present

    - name: creation du conteneur
      docker_container:
       name: test_app
       image: "{{ image_prod }}"
       ports: '8081:8080'
       state: started
       command: java -jar /usr/bin/devops-1.0.war
