# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # Create a forwarded port mapping which allows access to a specific port
  config.vm.network "forwarded_port", guest: 22, host: 8085
  # Share an additional folder to the guest VM. The first argument is
  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  # Customize the amount of memory on the VM:
      vb.memory = "2048"
  end
end
